[package]
name = "map"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer = { path = "../renderer" }
anyhow = { workspace = true }
wgpu-canvas = { workspace = true}

[build-dependencies]
anyhow = "1.0"

