[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
wgpu = { workspace = true}
wgpu_text = { git = "https://github.com/VladasZ/wgpu-text/", branch = "wgpu-28" }
wgpu-canvas = { workspace = true}

[build-dependencies]
anyhow = "1.0"


